run: if.cpp ifelse.cpp ifelseif.cpp or.cpp and.cpp more_and.cpp not.cpp cctypes.cpp condit.cpp switch.cpp enum.cpp jump.cpp cinfish.cpp cingolf.cpp outfile.cpp sumafile.cpp
	g++ if.cpp -o $@_if
	g++ ifelse.cpp -o $@_ifelse
	g++ ifelseif.cpp -o $@_ifelseif
	g++ or.cpp -o $@_or
	g++ and.cpp -o $@_and
	g++ more_and.cpp -o $@_more_and
	g++ not.cpp -o $@_not.cpp
	g++ cctypes.cpp -o $@_cctypes
	g++ condit.cpp -o $@_condit
	g++ switch.cpp -o $@_switch
	g++ enum.cpp -o $@_enum
	g++ jump.cpp -o $@_jump
	g++ cinfish.cpp -o $@_cinfish
	g++ cingolf.cpp -o $@_cingolf
	g++ outfile.cpp -o $@_outfile
	g++ sumafile.cpp -o $@_sumafile
