myfirst: myfirst.cpp carrots.cpp sqrt.cpp babysfirstfunc.cpp lbstostone.cpp
	g++ myfirst.cpp -o run_mayfirst
	g++ carrots.cpp -o run_carrots
	g++ sqrt.cpp -o run_sqrt -lm
	g++ babysfirstfunc.cpp -o run_babysfirstfunc
	g++ lbstostone.cpp -o run_lbstostone
