run: limits.cpp exceed.cpp hexoct1.cpp hexoct2.cpp chartype.cpp morechar.cpp bondini.cpp floatnum.cpp floatadd.cpp arith.cpp divide.cpp modulus.cpp init.cpp typecast.cpp
	g++ limits.cpp -o run_limits
	g++ exceed.cpp -o run_exceed
	g++ hexoct1.cpp -o run_hexoct1
	g++ hexoct2.cpp -o run_hexoct2
	g++ chartype.cpp -o run_chartype
	g++ morechar.cpp -o run_morechar
	g++ bondini.cpp -o run_bondini
	g++ floatnum.cpp -o run_floatnum
	g++ floatadd.cpp -o run_floatadd
	g++ arith.cpp -o run_arith
	g++ divide.cpp -o run_divide
	g++ modulus.cpp -o run_modulus
	g++ init.cpp -o run_init
	g++ typecast.cpp -o run_typecast
