run: calling.cpp protos.cpp twoarg.cpp lotto.cpp arrfun1.cpp arrfun2.cpp arrfun3.cpp arrfun4.cpp strfun.cpp strgback.cpp travel.cpp strctfun.cpp
	g++ calling.cpp -o run_calling
	g++ protos.cpp -o run_protos
	g++ twoarg.cpp -o run_twoarg
	g++ lotto.cpp -o run_lotto
	g++ arrfun1.cpp -o run_arrfun1
	g++ arrfun2.cpp -o run_arrfun2
	g++ arrfun3.cpp -o run_arrfun3
	g++ arrfun4.cpp -o run_arrfun4
	g++ strfun.cpp -o run_strfun
	g++ strgback.cpp -o run_strgback
	g++ travel.cpp -o run_travel
	g++ strctfun.cpp -o run_strctfun
