run: forloop.cpp num_test.cpp express.cpp formore.cpp bigstep.cpp forstr1.cpp plus_one.cpp
	g++ forloop.cpp -o run_forloop
	g++ num_test.cpp -o run_num_test
	g++ express.cpp -o run_express
	g++ formore.cpp -o run_formore
	g++ bigstep.cpp -o run_bigstep
	g++ forstr1.cpp -o run_forstr1
	g++ plus_one.cpp -o run_plus_one
