run: inline.cpp firstref.cpp secref.cpp swaps.cpp cubes.cpp strc_ref.cpp strquote.cpp
	g++ inline.cpp -o run_inline
	g++ firstref.cpp -o run_firstref
	g++ secref.cpp -o run_secref
	g++ swaps.cpp -o run_swaps
	g++ cubes.cpp -o run_cubes
	g++ strc_ref.cpp -o run_strc_ref
	g++ strquote.cpp -o run_strquote
