run: inline.cpp firstref.cpp secref.cpp swaps.cpp cubes.cpp strc_ref.cpp strquote.cpp filefunc.cpp left.cpp leftover.cpp funtemp.cpp twotemps.cpp twoswap.cpp tempover.cpp choices.cpp
	g++ -g choices.cpp -o run_choices
	g++ -g tempover.cpp -o run_tempover
	g++ -g twoswap.cpp -o run_twpswap
	g++ -g twotemps.cpp -o run_twotemps
	g++ -g funtemp.cpp -o run_funtemp
	g++ -g leftover.cpp -o run_leftover
	g++ -g left.cpp -o run_left
	g++ filefunc.cpp -o run_filefunc
	g++ inline.cpp -o run_inline
	g++ firstref.cpp -o run_firstref
	g++ secref.cpp -o run_secref
	g++ swaps.cpp -o run_swaps
	g++ cubes.cpp -o run_cubes
	g++ strc_ref.cpp -o run_strc_ref
	g++ strquote.cpp -o run_strquote
