#! /usr/bin/ruby
#

class BadProgrammer
	# This is used for getter and setter
	#
	attr_accessor :name, :height, :weight

	def initialize(n, h, w)
    		@name = n
		@height = h
		@weight = w
  	end
	
	# This module is essentially to use one command
	# to change all the instanced variables
	#
	def change_all_info(n, h, w)
		self.name = n
		self.height = h
		self.weight = w
	end

	def program
		"#{self.name}! You can do better! Just focus!"
	end

	def info
		"#{self.name} /  #{self.height} / #{self.weight}"
	end

	def lose_weight
		if self.weight > 180 && self.height < 60
			puts "Might need to lose weight"
		else
			puts "Probably healthy"
		end
	end
end

# We initalize the the class
#
shane = BadProgrammer.new("Shane", 63, 163)

# Call the program def that is inside the class
# Trying multiple print methods
#
p shane.program
puts shane.program
print shane.program, "\n"

# Testing a getter method
#
puts shane.name

# Testing a setter method
#
shane.name = "DoppleShane"
puts shane.info
shane.lose_weight
shane.change_all_info("NotShane", 63, 155)
puts shane.info
