run:
	g++ -g stock00.h stock00.cpp usestock0.cpp -o run_stock0
	g++ -g stock10.h stock10.cpp usestock1.cpp -o run_stock1
	g++ -g stock20.h stock20.cpp usestock2.cpp -o run_stock2
	g++ -g stack.h stack.cpp stacker.cpp -o run_stacker