run:
	g++ -g coordin.cpp coordin_func.cpp -o run_coordin
	g++ -g autoscp.cpp -o run_autoscp
	g++ -g external.cpp support.cpp -o run_external_support
	g++ -g twofile1.cpp twofile2.cpp -o run_twofiles
	g++ -g static.cpp -o run_static
	g++ -g newplace.cpp -o run_newplace
	g++ -g namesp.h namesp.cpp usenmsp.cpp -o run_namesp
